version: "3.8"

services:
  mysql_db_container:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=genetic-mutation
      - MYSQL_ROOT_PASSWORD=123456

  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - 8080:8080
